### PR TITLE
Do not migrate tasks to a different thread pool (backport of #1159)

### PR DESCRIPTION
**Pull request by Drvi**

### CODE REVIEW

**Comment by IanButterworth** [comment]
This seems like functionality Base should have. Is there a feature request for it?

**Comment by Drvi** [comment]
I think the tests are broken on 1.11+ because of we're touching internals that changed with the Memory PR.

**Comment by IanButterworth** [comment]
```
Threads.@spawn Threads.threadpool()
```
That looks good to me. Any reason not to use that?

**Review by NHDaly — APPROVED** [review]
makes sense to me 👍

**Pull request merged**
