### PR TITLE
In query key-value pairs, decode plus as space

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by garborg** [comment]
This seems off to me:
```jl
julia> HTTP.queryparams(HTTP.escapeuri(Dict("a+b" => "c d+e")))
Dict{String,String} with 1 entry:
  "a b" => "c d e"
```

**Comment by quinnj** [comment]
Why?

**Comment by garborg** [comment]
Is it wrong for values to have a literal "+", escaped as "%2B", and expect them to round trip to "+" after unescaping?

**Comment by garborg** [comment]
I.e. I thought"+"-decoding had to happen before pct-unescaping.

**Comment by quinnj** [comment]
Yeah, you're right. My bad. I rushed this a bit. I've got a fix incoming.

**Pull request merged**
