### PR TITLE
Fix a deprecation warning in `request_uri(url, query)`

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
CI is not running on this PR because `JuliaWeb` has run out of free Travis OSS credits.

See also: #628 (Set up GitHub Actions CI on this repository)

**Comment by DilumAluthge** [comment]
@c42f Is this the correct way to fix this deprecation warning?

**Comment by c42f** [comment]
Yes. You'll need to upgrade the version of URLs though.

We're in a bit of a weird state with the smantics of deprecation warnings which IIRC are off by default in 1.5 but on in earlier releases...

**Comment by DilumAluthge** [comment]
> Yes. You'll need to upgrade the version of URLs though.

Done.

**Review by quinnj — APPROVED** [review]

**Comment by DilumAluthge** [comment]
@quinnj Would it be possible to get a new release of HTTP.jl with this?

**Pull request merged**
