### PR TITLE
Make debugging macros insert branches on DEBUG_LEVEL

### PR DESCRIPTION
**Pull request by ararslan**
This now makes them behave as expected after #354:
```
julia> HTTP.AWS4AuthRequest.sign_aws4!("GET",
                                       URI("https://example.amazonaws.com/"),
                                       Headers([]),
                                       UInt8[];
                                       timestamp=DateTime(2015, 8, 30, 12, 36),
                                       aws_service="service",
                                       aws_region="us-east-1")
"Authorization" => "AWS4-HMAC-SHA256 Credential=AKIDEXAMPLE/20150830/us-east-1/service/aws4_request, SignedHeaders=content-md5;x-amz-content-sha256;x-amz-date, Signature=4308f0826e002c8afb1beba5866ac50182d4958a2bdbb85177c1397b769c322f"

julia> HTTP.DEBUG_LEVEL[] = 3
3

julia> HTTP.AWS4AuthRequest.sign_aws4!("GET",
                                       URI("https://example.amazonaws.com/"),
                                       Headers([]),
                                       UInt8[];
                                       timestamp=DateTime(2015, 8, 30, 12, 36),
                                       aws_service="service",
                                       aws_region="us-east-1")
DEBUG: 2018-11-30T16:28:35.053 9f6b AWS4 canonical_form: GET
/

content-md5:1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20150830T123600Z

content-md5;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
DEBUG: 2018-11-30T16:28:35.053 9f6b AWS4 string_to_sign: AWS4-HMAC-SHA256
20150830T123600Z
20150830/us-east-1/service/aws4_request
5f231d3262389a81a957ee6120f6c3eafac690d565baae5f8aeff146ea759baf
DEBUG: 2018-11-30T16:28:35.053 9f6b AWS4 signature: 4308f0826e002c8afb1beba5866ac50182d4958a2bdbb85177c1397b769c322f
"Authorization" => "AWS4-HMAC-SHA256 Credential=AKIDEXAMPLE/20150830/us-east-1/service/aws4_request, SignedHeaders=content-md5;x-amz-content-sha256;x-amz-date, Signature=4308f0826e002c8afb1beba5866ac50182d4958a2bdbb85177c1397b769c322f"
```

### CODE REVIEW

**Comment by omus** [comment]
Some benchmarks would be nice here

**Comment by quinnj** [comment]
@ararslan, what are your thoughts here? Sorry for the slow delay; I'm going to try and make a push on things here. I'd support having DEBUG be a Ref; the perf cost would be minimal and makes things easily configurable (as long we keep the debug statements at reasonable levels).

**Comment by ararslan** [comment]
Haven't thought about this for a while. Not sure how best to benchmark it, but I agree, I think something like this would be nice. Don't know when I'll have time to revisit this PR though.

**Comment by quinnj** [comment]
Merging as I've wanted this for a while; I know we want to overhaul the overall logging/debugging situation in HTTP.jl, but that doesn't prevent us from having this in the mean time.

**Comment by ararslan** [comment]
Holy cow, this is an old one, I had forgotten all about it. Glad it's useful!

**Pull request merged**
