### PR TITLE
Enhancement for HTTP.WebScoekts.listen() and WebSockets Server Handler

### PR DESCRIPTION
**Pull request by zhanglix**
* add HTTP.Request to WebSocket for server handler.  
  WebSocket Server can provide different service for different URI
* support optional keyword for HTTP.listen() to  HTTP.WebSockets.listen(). 
  All unrecognized keyword args to HTTP.WebSockets.listen() will be passed through to HTTP.listen()

### CODE REVIEW

**Comment by zhanglix** [comment]
could  anybody have a look at these  failed checks?

this PR is  for https://github.com/JuliaWeb/HTTP.jl/pull/566

**Comment by zhanglix** [comment]
@samoconnor  could you have a look at this PR? It seems you are the major contributor to the related code. 

Is it possible to merge it to provide these enhancements to HTTP.WebSockets?

**Comment by mattBrzezinski** [comment]
> @samoconnor could you have a look at this PR? It seems you are the major contributor to the related code.

Sam O'Connor hasn't been active on GitHub for quite some time. Hopefully someone else in the GH Org can lend a hand, I'm quite busy currently but at some point in the future I can carve out time to look this over.

**Comment by zhanglix** [comment]
> Sam O'Connor hasn't been active on GitHub for quite some time. Hopefully someone else in the GH Org can lend a hand, I'm quite busy currently but at some point in the future I can carve out time to look this over.

@mattBrzezinski Thank you! It is great to get some response!  😃 

BTW. It seems that the failed unit tests on some architecture are due to unstable network conditions.  Maybe refactor those tests to only depend on local server would be a good idea.

**Comment by quinnj** [comment]
This looks fine to me, though I'm unfamiliar with the websockets code in general; that said, I'm very much in favor of encouraging anyone who is willing to step up and give this code some love. There's a bunch of open issues labelled `websockets` that would be awesome if someone is willing to help out.

**Pull request merged**
