### PR TITLE
Implement HTTP.StatusHeaders as a "partial" Response

### PR DESCRIPTION
**Pull request by fredrikekre**
This allows for "previewing" the status code and
headers from an in-flight asynchronous HTTP request.

Example:
```
sh = HTTP.StatusHeaders()
req = @async HTTP.get("https://github.com", status_headers=sh)

fetch(sh) # Blocks until status and headers are ready
# Do something with status/headers while body is still transmitting

fetch(req) # Blocks until body is ready
```

Fixes https://github.com/JuliaWeb/HTTP.jl/issues/662.

### CODE REVIEW

**Comment by fredrikekre** [comment]
cc @staticfloat

**Comment by staticfloat** [comment]
Needs tests, but looks good to me!  I think it would be good to test getting the status/headers of both a redirect and the eventual target of the redirect.

**Comment by quinnj** [comment]
Do we still need this for some reason, given the alternative solution proposed in #662?

**Comment by fredrikekre** [comment]
Probably not; this is essentially the `startwrite` call from https://github.com/JuliaWeb/HTTP.jl/issues/662#issuecomment-759657721

**Pull request closed without merging**
