### PR TITLE
Update for 0.7/1.0

### PR DESCRIPTION
**Pull request by oxinabox**

### CODE REVIEW

**Comment by oxinabox** [comment]
I just checked over the `if VERSION ...` blocks.
to my surprise i actually got them all correct AFAICT 

All the conditions and stuff should be solved.
This does need femtocleaning to get ride of a deprecation I introduced,

I am note sure what is with the failure.

**Comment by samoconnor** [comment]
Probably should delete `client.jl` at the same time as dropping 0.6 support: https://github.com/JuliaWeb/HTTP.jl/issues/250#issuecomment-395248642

**Comment by samoconnor** [comment]
This should also cover #283

**Comment by oxinabox** [comment]
#283 seems like a separate problem.
I just want to get the 0.7 transition done, and compat cruft removed.
Isn't that a bug present in 0.6?

**Comment by oxinabox** [comment]
Can someone with a bit more experience at the workings of this package take a look at the remaining errors. (@quinnj, @samoconnor).
I don't think they are directly related to any deprecations, but maybe are related to something I changed.

Also can Femtocleaner be waved over this?
It has a deprecation here that I think it can fix.

**Comment by quinnj** [comment]
Closed in favor of https://github.com/JuliaWeb/HTTP.jl/pull/290 (since I can't push to @oxinabox 's fork)

**Comment by oxinabox** [comment]
Sorry, idk why you can't push to my fork.
Thanks

**Pull request closed without merging**
