### PR TITLE
Do not call `close()` on the `response_stream`

### LINKED ISSUE #543: `response_stream` breaks with `IOBuffer()`
Versions:

```
Julia 1.4.1 
HTTP.jl 0.8.15
```

Example:
```julia
using HTTP
io = IOBuffer(read=true, write=true)
HTTP.get("https://google.com", response_stream=io)
```

Which results in:
```
ERROR: ArgumentError: ensureroom failed, IOBuffer is not writeable
Stacktrace:
 [1] ensureroom_slowpath(::Base.GenericIOBuffer{Array{UInt8,1}}, ::UInt64) at ./iobuffer.jl:298
 [2] ensureroom at ./iobuffer.jl:320 [inlined]
 [3] unsafe_write(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Ptr{UInt8}, ::UInt64) at ./iobuffer.jl:414
 [4] unsafe_write at ./io.jl:593 [inlined]
 [5] write at ./io.jl:616 [inlined]
 [6] write(::Base.GenericIOBuffer{Array{UInt8,1}}, ::HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext}}) at ./io.jl:663
 [7] readbody at /home/sabae/.julia/packages/HTTP/BOJmV/src/StreamRequest.jl:146 [inlined]
 [8] macro expansion at /home/sabae/.julia/packages/HTTP/BOJmV/src/StreamRequest.jl:67 [inlined]
 [9] macro expansion at ./task.jl:334 [inlined]
 [10] request(::Type{StreamLayer{Union{}}}, ::HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext}, ::HTTP.Messages.Request, ::Array{UInt8,1}; response_stream::Base.GenericIOBuffer{Array{UInt8,1}}, iofunction::Nothing, verbose::Int64, kw::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/sabae/.julia/packages/HTTP/BOJmV/src/StreamRequest.jl:56
 [11] request(::Type{ConnectionPoolLayer{StreamLayer{Union{}}}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::Array{UInt8,1}; proxy::Nothing, socket_type::Type{T} where T, reuse_limit::Int64, kw::Base.Iterators.Pairs{Symbol,Union{Nothing, Base.GenericIOBuffer{Array{UInt8,1}}},Tuple{Symbol,Symbol},NamedTuple{(:iofunction, :response_stream),Tuple{Nothing,Base.GenericIOBuffer{Array{UInt8,1}}}}}) at /home/sabae/.julia/packages/HTTP/BOJmV/src/ConnectionRequest.jl:89
 [12] request(::Type{ExceptionLayer{ConnectionPoolLayer{StreamLayer{Union{}}}}}, ::HTTP.URIs.URI, ::Vararg{Any,N} where N; kw::Base.Iterators.Pairs{Symbol,Union{Nothing, Base.GenericIOBuffer{Array{UInt8,1}}},Tuple{Symbol,Symbol},NamedTuple{(:iofunction, :response_stream),Tuple{Nothing,Base.GenericIOBuffer{Array{UInt8,1}}}}}) at /home/sabae/.julia/packages/HTTP/BOJmV/src/ExceptionRequest.jl:19
 [13] (::Base.var"#58#60"{Base.var"#58#59#61"{ExponentialBackOff,HTTP.RetryRequest.var"#2#3"{Bool,HTTP.Messages.Request},typeof(HTTP.request)}})(::Type{T} where T, ::Vararg{Any,N} where N; kwargs::Base.Iterators.Pairs{Symbol,Union{Nothing, Base.GenericIOBuffer{Array{UInt8,1}}},Tuple{Symbol,Symbol},NamedTuple{(:iofunction, :response_stream),Tuple{Nothing,Base.GenericIOBuffer{Array{UInt8,1}}}}}) at ./error.jl:288
 [14] #request#1 at /home/sabae/.julia/packages/HTTP/BOJmV/src/RetryRequest.jl:44 [inlined]
 [15] request(::Type{MessageLayer{RetryLayer{ExceptionLayer{ConnectionPoolLayer{StreamLayer{Union{}}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Array{UInt8,1}; http_version::VersionNumber, target::String, parent::HTTP.Messages.Response, iofunction::Nothing, kw::Base.Iterators.Pairs{Symbol,Base.GenericIOBuffer{Array{UInt8,1}},Tuple{Symbol},NamedTuple{(:response_stream,),Tuple{Base.GenericIOBuffer{Array{UInt8,1}}}}}) at /home/sabae/.julia/packages/HTTP/BOJmV/src/MessageRequest.jl:51
 [16] request(::Type{BasicAuthLayer{MessageLayer{RetryLayer{ExceptionLayer{ConnectionPoolLayer{StreamLayer{Union{}}}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Array{UInt8,1}; kw::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol},NamedTuple{(:response_stream, :parent),Tuple{Base.GenericIOBuffer{Array{UInt8,1}},HTTP.Messages.Response}}}) at /home/sabae/.julia/packages/HTTP/BOJmV/src/BasicAuthRequest.jl:28
 [17] request(::Type{RedirectLayer{BasicAuthLayer{MessageLayer{RetryLayer{ExceptionLayer{ConnectionPoolLayer{StreamLayer{Union{}}}}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Array{UInt8,1}; redirect_limit::Int64, forwardheaders::Bool, kw::Base.Iterators.Pairs{Symbol,Base.GenericIOBuffer{Array{UInt8,1}},Tuple{Symbol},NamedTuple{(:response_stream,),Tuple{Base.GenericIOBuffer{Array{UInt8,1}}}}}) at /home/sabae/.julia/packages/HTTP/BOJmV/src/RedirectRequest.jl:24
 [18] request(::String, ::String, ::Array{Pair{SubString{String},SubString{String}},1}, ::Array{UInt8,1}; headers::Array{Pair{SubString{String},SubString{String}},1}, body::Array{UInt8,1}, query::Nothing, kw::Base.Iterators.Pairs{Symbol,Base.GenericIOBuffer{Array{UInt8,1}},Tuple{Symbol},NamedTuple{(:response_stream,),Tuple{Base.GenericIOBuffer{Array{UInt8,1}}}}}) at /home/sabae/.julia/packages/HTTP/BOJmV/src/HTTP.jl:314
 [19] #get#12 at /home/sabae/.julia/packages/HTTP/BOJmV/src/HTTP.jl:391 [inlined]
 [20] top-level scope at REPL[12]:3
```

### PR DESCRIPTION
**Pull request by c42f**
This allows a plain `IOBuffer` to be used with `response_stream`.

It seems unnecessary to be calling `close(response_stream)` inside
HTTP.request() - given that HTTP.request is a blocking operation, the
caller can easily close the stream themselves after `HTTP.request()`
returns.

This could be considered a breaking change for users who use the
internal IO type Base.BufferStream with the response_stream keyword.

Fixes #543

### CODE REVIEW

**Review by quinnj — APPROVED** [review]
LGTM; I'm disappointed in the testing situation. I thought using the pie-socket site for the websocket tests would work well, but the failures in the CI here seem like random failures.

**Comment by c42f** [comment]
Downloads.jl uses `httpbingo.julialang.org` for testing, but unfortunately I don't think that supports websockets.

Are we happy to merge right away, even though this is arguably breaking?

**Comment by quinnj** [comment]
Yeah, fine by me

**Comment by omus** [comment]
Can we get a release that includes this fix?

**Comment by fredrikekre** [comment]
https://github.com/JuliaWeb/HTTP.jl/pull/769

**Pull request merged**
