### PR TITLE
mark recoverability of DNS erros correctly

### PR DESCRIPTION
**Pull request by tanmaykm**
This changes HTTP client to not retry on certain DNS errors. From the [list of possible DNS errors](https://github.com/JuliaLang/julia/blob/ec8df3da3597d0acd503ff85ac84a5f8f73f625b/stdlib/Sockets/src/addrinfo.jl#L108-L112) only EAI_AGAIN may be recoverable. This also changes the error code comparison to use `UV_EAI_AGAIN`, because that is what a [DNSError instance would contain](https://github.com/JuliaLang/julia/blob/ec8df3da3597d0acd503ff85ac84a5f8f73f625b/stdlib/Sockets/src/addrinfo.jl#L108-L112).

fixes: #1085

### CODE REVIEW

**Review by quinnj — APPROVED** [review]

**Comment by nickrobinson251** [comment]
can we add a test please?

**Comment by tanmaykm** [comment]
We had faced this in a likely stressed condition in our application. I was testing this with a modified julia binary to artificially throw the DNS error. I found it hard to replicate the error otherwise.

I could add a unit test for `isrecoverable`, maybe that would be useful?

**Comment by tanmaykm** [comment]
@nickrobinson251  Actually I think I can add some relevant tests. And I also missed out some more changes to `isrecoverable`. PR in a bit.

**Comment by nickrobinson251** [comment]
> I think I can add some relevant tests

Thanks!

> a unit test for isrecoverable, maybe that would be useful?

yeah, i think unit tests would be helpful

**Pull request merged**
