### PR TITLE
Separate HTTP.request from Layers.request

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by quinnj** [comment]
I like the changes here; what's the status @fredrikekre ? I see it's still marked WIP?

**Comment by fredrikekre** [comment]
I can update it if you want, wasn't sure the changes were desired and, hence, the draft.

This will break packages that insert their own layers, but maybe that is just the AWS packages? Either it needs a breaking new version here or those packages need to be fixed.

**Comment by quinnj** [comment]
I'd ideally like to get #486 and this PR into a new minor release soon; @fredrikekre, are you able/willing to update here?

**Comment by fredrikekre** [comment]
Sure.

**Review by quinnj — APPROVED** [review]
This LGTM now. @mattBrzezinski @oxinabox @omus @iamed2 , will this break existing custom layers people have defined elsewhere? If so, we can rename the PR to `[BREAKING]` and try to announce the change.

**Comment by mattBrzezinski** [comment]
> This LGTM now. @mattBrzezinski @oxinabox @omus @iamed2 , will this break existing custom layers people have defined elsewhere? If so, we can rename the PR to `[BREAKING]` and try to announce the change.

If you remove the `Layers` prefix, [here](https://github.com/JuliaWeb/HTTP.jl/pull/469/files#diff-153988f7f3c9bc5027f0e2f5adc73a5749aa9fb39709ed9af21eee15592251efR8), and the tests fail then it'll be a breaking change.

**Comment by quinnj** [comment]
@fredrikekre, are you up for updating this PR to get it merged soon for a 1.0 release?

**Comment by quinnj** [comment]
Included in #789

**Pull request closed without merging**
