### PR TITLE
FIX UndefRefError to x in cookies.jl

### PR DESCRIPTION
**Pull request by raffopazzo**

### CODE REVIEW

**Comment by raffopazzo** [comment]
Not tested and may not be the correct thing to do. Just wanted to point out the issue

**Comment by fredrikekre** [comment]
LGTM but of course would be good with a test

**Comment by raffopazzo** [comment]
I don't know exactly what's wrong. I just saw this happen once and I thought I'd report it to you but trying to write it up in an issue was more complicated then showing you where the issue is :D

**Review by quinnj — APPROVED** [review]
Yeah, good catch. This was ported directly over from the go code, so I must have just missed this in the translation. I also ported their tests over, so I guess they didn't have a test covering this. This is kind of a random feature though, because it's really just saying, hey, there was something in the `Cookie` that doesn't have a semantic meaning, so stick in this `unparsed` field. So probably not super common.

**Pull request merged**
